logs-example/support-shift-scheduler-input.json
logs-example/support-shift-scheduler-output.json

Signed-off-by: Stevche Radevski <stevche@balena.io>

Change sample input to camelcase, reduce timeout duration

---

helper-scripts/send-calendar-invites.js

send-calendar-invites: Change const statement to let

---

algo-core/ortools_solver.py
helper-scripts/beautify-schedule.js
helper-scripts/download-and-configure-input.js
helper-scripts/send-calendar-invites.js
lib/gsheets.js
lib/schemas/support-shift-scheduler-input.schema.json
lib/schemas/support-shift-scheduler-output.schema.json

Change-type: minor
Signed-off-by: JuanFRidano <juanfr@balena.io>

extend support hours to following day and make tracks configurable

---

.env.dist
.gitignore
algo-core/onboarding.py
algo-core/ortools_solver.py
algo-core/scheduler_utils.py
helper-scripts/beautify-schedule.js
helper-scripts/download-and-configure-input.js
helper-scripts/options/balena.json
helper-scripts/options/productOS.json
helper-scripts/options/summit.json
helper-scripts/send-calendar-invites.js
lib/gauth.js
lib/gsheets.js
lib/schemas/support-shift-scheduler-input.schema.json
lib/schemas/support-shift-scheduler-output.schema.json
package-lock.json
package.json
poetry.lock
pyproject.toml

we should merge this into master since it is the latest version

Adding max hours week

---

helper-scripts/download-and-configure-input.js
helper-scripts/options/balenaio.json
helper-scripts/options/devOps.json
helper-scripts/options/productOS.json
helper-scripts/send-calendar-invites.js
lib/gauth.js
lib/gsheets.js

Signed-off-by: JuanFRidano <juanfr@balena.io>

extend support options

---

algo-core/onboarding.py
helper-scripts/options/balenaio.json
helper-scripts/options/productOS.json

Various small option updates

---

algo-core/ortools_solver.py
helper-scripts/beautify-schedule.js

Update output to include @@support_ops

---

helper-scripts/beautify-schedule.js

Allow beautifying a schedule containing any number of days

---

helper-scripts/beautify-schedule.js
helper-scripts/download-and-configure-input.js
helper-scripts/send-calendar-invites.js
lib/gauth.js
lib/gsheets.js
package-lock.json
package.json

Update to use @balena/lint for linting

---

package-lock.json
package.json

Remove `fs` from package.json - it's a built in module

---

helper-scripts/beautify-schedule.js
helper-scripts/download-and-configure-input.js
helper-scripts/send-calendar-invites.js
lib/gauth.js
lib/gsheets.js
lib/validate-json.js
package-lock.json
package.json
tsconfig.json

Add type-checking for js files

---

helper-scripts/beautify-schedule.js
helper-scripts/download-and-configure-input.js

Allow beautify-schedule to work for any length of "day"

---

helper-scripts/send-calendar-invites.js

Use standard date methods/math for handling calendar invite dates

---

README.md
helper-scripts/download-and-configure-input.ts
helper-scripts/send-calendar-invites.ts
lib/gauth.ts
lib/gsheets.ts
lib/validate-json.ts
package-lock.json
package.json

Conversion to typescript

---

README.md
helper-scripts/options/devOps.json
helper-scripts/set-victorops-schedule.ts
package-lock.json
package.json

Add set-victorops-schedule script for the devops schedule in victorops

---

helper-scripts/send-calendar-invites.ts
helper-scripts/set-victorops-schedule.ts
lib/validate-json.ts

This avoids needing to pass the full path since it can be inferred from
those two elements
Change-type: major

Change send-calendar-invites to accept the date and schedule name

---

README.md
helper-scripts/beautify-schedule.ts
package.json

Convert beautify-schedule to ts and accept the date and schedule name

---

lib/gsheets.ts

Clean up fetching of gsheets agents data

---

algo-core/scheduler_utils.py

Include `agentName` in the output for use in set-victorops-schedule

---

README.md
helper-scripts/beautify-schedule.ts
package-lock.json
package.json

Avoid timezone issues when beautifying the schedule

---

poetry.lock

Update ortools to 9.0

---

pyproject.toml

Add missed file for ortools update

---

helper-scripts/options/balenaio.json

helper-scripts/options/balenaio.json: Tweak custom settings

---

README.md

Remove next cycle date reference from README

---

helper-scripts/options/balenaio.json

Remove Jordan from the list of agents

---

helper-scripts/download-and-configure-input.ts

Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Passes null as a required second argument to mkdirpAsync.

---

helper-scripts/beautify-schedule.ts

Signed-off-by: Pranas Ziaukas <pranas@balena.io>

Apply the latest code styling

---

helper-scripts/options/devOps.json

Remove Matt from the list of devOps

---

helper-scripts/options/balenaio.json
package-lock.json

Update balena.io options

---

helper-scripts/options/devOps.json

Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Add 20k-ultra & Ereski to DevOps rotation.

---

algo-core/ortools_solver.py
algo-core/scheduler_utils.py

Allow specifying valid availability values

---

.huskyrc
.lintstagedrc
helper-scripts/beautify-schedule.ts
package-lock.json
package.json

Update swaps portion of Flowdock message

---

algo-core/src/process_input.py
helper-scripts/options/balenaio.json

Reconfigure support coverage based on available teamwork hours

---

README.md
algo-core/src/process_input.py

Update README to reflect new script config in Teamwork Model

---

helper-scripts/options/devOps.json
logs/example/nocover.json

Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Adds olamiko to the list of DevOps agents.

---

repo.yml

Add repo.yml for flowzone versioning

---

helper-scripts/send-calendar-invites.ts

Change ack reference from JF thread to Zulip stream

---

.env.dist
.husky/pre-commit
.huskyrc
README.md
algo-core/src/custom_var_domains.py
algo-core/src/onboarding.py
algo-core/src/process_input.py
algo-core/src/read_input.py
algo-core/src/solve_model.py
algo-core/src/veterans.py
helper-scripts/beautify-schedule.ts
helper-scripts/download-and-configure-input.ts
helper-scripts/options/balenaio.json
helper-scripts/options/devOps.json
helper-scripts/options/productOS.json
helper-scripts/options/supportAuditing.json
helper-scripts/send-calendar-invites.ts
helper-scripts/set-victorops-schedule.ts
lib/gauth.ts
lib/gsheets.ts
lib/schemas/support-shift-scheduler-input.schema.json
lib/validate-json.ts
package-lock.json
package.json

Retire deprecated alternative OAuth2 method

---

helper-scripts/beautify-schedule.ts
helper-scripts/download-and-configure-input.ts
helper-scripts/send-calendar-invites.ts
helper-scripts/set-victorops-schedule.ts

These changes allow the scripts to be used with conditions to stop a workflow in case of failures to write or interact with an external resource.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Helper scripts now use non-zero exit codes during write failure.

---

helper-scripts/beautify-schedule.ts

This makes the output compatible with Zulip for pings and formatting.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Updates the format of the beautify helper script.

---

helper-scripts/options/balenaio.json

Reduce balenaio support coverage hours from 36 to 27 per week. Update agent distribution.

Reduce coverage hours

---

.env.dist
helper-scripts/beautify-schedule.ts
package-lock.json
package.json

Convert teamwork handles to Zulip handles.

---

helper-scripts/options/devOps.json

Adds aethernet to the devOps VO userlist.

---

.github/dependabot.yml
.github/workflows/flowzone.yml

remove dependabot

---

helper-scripts/options/devOps.json
pyproject.toml

Add Harald's VO username

---

README.md
helper-scripts/send-calendar-invites.ts

Signed-off-by: Pranas Ziaukas <pranas@balena.io>

Rename `support` to `support-operations`

---

helper-scripts/beautify-schedule.ts

Make Zulip email conversion case insensitive.

---

helper-scripts/options/devOps.json

Add otaviojacobi to the DevOps rotation.
